from pages.login_page import Login
from pages.homepage import NavigationBar
from pages.my_info_page import PersonalDetails



def test_my_info_page(start):
    login = Login(start)
    login.valid_login()
    homepage = NavigationBar(start)
    homepage.enter_my_info()
    n = PersonalDetails(start)
    n.fill_employee_full_name("Varazdat", "Hmayaki", "Kazduryan")
    n.fill_nickname("Kyaj")
    n.fill_employee_id("0012")
    n.fill_other_id("000167")
    n.fill_drivers_license("A123465")
    n.pick_expiry_date("12", "October", "2023")
    n.fill_SSN("007")
    n.fill_SIN(123)
    n.select_nationality("Mexican")
    n.marital_status("Married")
    n.pick_date_of_birth("1995", "November", "16")
    n.select_gender("female")
    n.fill_military_service("Askeran")
    n.smoking_checkbox_click()
    n.save_button_click()
    assert n.is_success_message_displayed()
    assert n.is_first_name_correct("Varazdat")
    assert n.is_middle_name_correct("Hmayaki")
    assert n.is_last_name_correct("Kazduryan")
    assert n.is_nickname_correct("Kyaj")
    assert n.is_employee_id_correct("0012")
    assert n.is_other_id_correct("000167")
    assert n.is_drivers_license_correct("A123465")
    assert n.is_expiry_date_correct("2023-10-12", "12-10-2023")
    assert n.is_SSN_number_correct("007")
    assert n.is_SIN_number_correct(123)
    assert n.is_nationality_correctly_chosen("Mexican")
    assert n.is_marital_status_correct("married")
    assert n.is_date_of_birth_correct("1995-11-16", "16-11-1995")
    assert not n.is_male_selected()
    assert n.is_female_selected()
    assert n.is_military_service_correct("Askeran")
    assert not n.is_smoking_checkbox_selected()
